[user]
name = "Tom Houlé"
email = "tom@tomhoule.com"

[templates]
git_push_bookmark = '"tomhoule-" ++ change_id.short()'

[aliases]
no = ["new", "main@origin"]
# Find the closest ancestor with a bookmark pointing at it, and move it to the
# parent of the working copy.
#
# From https://gist.github.com/thoughtpolice/8f2fd36ae17cd11b8e7bd93a70e31ad6#file-jjconfig-toml
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[merge-tools.mergiraf]
program = "mergiraf"
merge-args = ["merge", "$base", "$left", "$right", "-o", "$output", "--fast"]
merge-conflict-exit-codes = [1]
conflict-marker-style = "git"

[signing]
behavior = "own"
backend = "ssh"
key = "/home/tom/.ssh/id_ed25519.pub"
